// Generated by CoffeeScript 1.3.3
(function() {
  var Connection, Future,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  Future = require('fibers/future');

  module.exports = Connection = (function() {

    function Connection(connection) {
      this.connection = connection;
      this.query = __bind(this.query, this);

    }

    Connection.prototype.query = function() {
      var args, f, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      f = new Future;
      args.push(f.resolver());
      (_ref = this.connection).query.apply(_ref, args);
      return f.wait();
    };

    return Connection;

  })();

}).call(this);
