// Generated by CoffeeScript 1.3.3
(function() {
  var Connection, Future, pg;

  pg = require('pg');

  Future = require('fibers/future');

  Connection = require('./connection');

  exports.connect = function(params) {
    var conn, f;
    f = new Future;
    pg.connect(params, f.resolver());
    conn = f.wait();
    return new Connection(conn);
  };

}).call(this);
