// Generated by CoffeeScript 1.3.3
(function() {
  var Connection, Future, pg;

  pg = require('pg');

  Future = require('fibers/future');

  Connection = require('./connection');

  exports.connect = function(params) {
    var conn, f;
    conn = pg.connect(params, (f = new Future).resolver()) && f.wait();
    return new Connection(conn);
  };

}).call(this);
